
language: java
sudo: false
jdk:
  - oraclejdk8

addons:
  sonarqube: true
  apt:
    packages:
      - oracle-java8-installer
      
install: true
script: mvn verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./travis.sh
